kind: Deployment
apiVersion: apps/v1
metadata:
  name: rtsp-buffer
  labels:
    app: rtsp-buffer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-buffer
  template:
    metadata:
      labels:
        app: rtsp-buffer
    spec:
      containers:
        - name: rtsp-buffer
          image: hexadtech/rtsp-buffer:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: rtsp-buffer-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30033
  selector:
    app: rtsp-buffer