kind: Deployment
apiVersion: apps/v1
metadata:
  name: barcode-reader
  labels:
    app: barcode-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barcode-reader
  template:
    metadata:
      labels:
        app: barcode-reader
    spec:
      containers:
        - name: barcode-reader
          image: hexadtech/scanner-emulator:latest
          imagePullPolicy: Always
          ports:
            - name: flask-http
              containerPort: 5000
              hostPort: 5000
              protocol: TCP
          env:
            - name: MQTT_HOST
              value: "mqttserver-svc.default"
            - name: CLIENT_CERTIFICATE
              value: |
                UEsDBAoAAAAAADg3JlGQjw/gqAUAAKgFAAAdAAAAMTU5OTM3NTQ2NjY3M19jZXJ0aWZpY2F0ZS5j
                cnQtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRUFEQ0NBdWlnQXdJQkFnSVVJWTRiOXVa
                enNMbWhYaDY3dXhCSzhzbUNibFl3RFFZSktvWklodmNOQVFFTApCUUF3YlRFTE1Ba0dBMVVFQmhN
                Q1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RVRBUEJnTlZCQWNUCkNGTmhiaUJLYjNO
                bE1SUXdFZ1lEVlFRS0V3dE9kWFJoYm1sNExVbHZWREVMTUFrR0ExVUVDeE1DUTBFeEV6QVIKQmdO
                VkJBTVRDazUxZEdGdWFYZ2dRMEV3SUJjTk1qQXdPVEEyTURZMU16QXdXaGdQTWpBMU1EQTRNekF3
                TmpVegpNREJhTUhBeEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxo
                TVJFd0R3WURWUVFICkV3aFRZVzRnU205elpURVFNQTRHQTFVRUNoTUhUblYwWVc1cGVERVJNQThH
                QTFVRUN4TUlVMmhsY214dlkyc3gKRkRBU0JnTlZCQU1UQzIxeGRIUXRZMnhwWlc1ME1JSUJJakFO
                QmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdjMWJuUkh3Z3BXalhZV1o2SzFP
                T1AzQTlUK2k2Z0QycGp1L1ZHRWRCUWx0b0NPaHlkRHBxN1Y2Cm1YMEdCQnF2MURTY09DMlhFaU9z
                UWdwYlRQWTY3MXNYcWxERkZraTU3cHZYT0ltWWpvdTZCTjZxTzRkWDhTa08Kb2FhZ2lFTGhxdUox
                RlM0dWx1TlNtQ2prZjl4YmtjcVpCTWhmU0pFQVBueUFtbXRCMXgwclBXRzdFN09kQzMybgpKUUlO
                ZFJNQTUwVXhnTG9FUjljOEprT2pLcnh6RWFLQWV6Q3ZQa3Z5ZGN4Y1U3S21samdvM3E3L3RQc3JW
                N3FJClJacGp2aGZKY3BWRytQSFZER2ZWd0txbmw5cS9lNmtJL1BkSmdVTHRaWFkrakFPTjVTL0ZF
                b2x6TThob3NaRG8KaFdLTlk0SzUzMlFvMFlNdkw0WXNVWFhIUDhqd1J3SURBUUFCbzRHU01JR1BN
                QTRHQTFVZER3RUIvd1FFQXdJRgpvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQWpBTUJnTlZI
                Uk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNyCklETW9KVlM4aFdaU1RoWkFvekdTRGQ4Uk5qQWZC
                Z05WSFNNRUdEQVdnQlJyQjVreUd5V2tFRnNIaTN2Tkw2cjcKT3lIREFEQWFCZ05WSFJFRUV6QVJn
                Z2xzYjJOaGJHaHZjM1NIQkg4QUFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUFCVnlHSVF0
                dTZrSlN2V2Z1dXZwaDRIdzA2WWxUSjlxSFNWSE10dFBnaGpHeHAwRzk5VlZTUjlZK1JKCmt1OVRO
                a2VLZHNWWXVCS0x0SFFCOFIzOFRDWXE4RGU1dU1Vb1gzQlFhRE1kQ0h5MmRDZ3JtTlg4aHkrR3pO
                bkkKWkdHM3JwMzlCdm9PN1BTNDdvQzloMmJ5bXgyQ1RnZTlGT1VEL2RYNjNyY2lsa3BBM0xzblZJ
                NVhlTDF5bUVCQwprYmVCdzFvazlyNjBPWFdacGREUGx0dzQ4RlY0Z1NrTnUrWjFXNEdmM1pFMzVR
                QU1rR2lHK2JpQWwvNjN5cm5KCk1MOFBvZ01UcmNzdHRKQTlBUU83cEtwSTRvZVNyZUR6YStaOEM1
                Ymg3Um11UDVMY0Nibml2bjZuNlExN2UxY0wKZC95UnBaY3Axd2E3VUU0eU1Vbkl4NmJUSkR3PQot
                LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tClBLAwQKAAAAAAA4NyZRi74hbYsGAACLBgAAHAAAADE1
                OTkzNzU0NjY2NzNfcHJpdmF0ZUtleS5rZXktLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0t
                Ck1JSUVvd0lCQUFLQ0FRRUF3YzFiblJId2dwV2pYWVdaNksxT09QM0E5VCtpNmdEMnBqdS9WR0Vk
                QlFsdG9DT2gKeWREcHE3VjZtWDBHQkJxdjFEU2NPQzJYRWlPc1FncGJUUFk2NzFzWHFsREZGa2k1
                N3B2WE9JbVlqb3U2Qk42cQpPNGRYOFNrT29hYWdpRUxocXVKMUZTNHVsdU5TbUNqa2Y5eGJrY3Fa
                Qk1oZlNKRUFQbnlBbW10QjF4MHJQV0c3CkU3T2RDMzJuSlFJTmRSTUE1MFV4Z0xvRVI5YzhKa09q
                S3J4ekVhS0FlekN2UGt2eWRjeGNVN0ttbGpnbzNxNy8KdFBzclY3cUlSWnBqdmhmSmNwVkcrUEhW
                REdmVndLcW5sOXEvZTZrSS9QZEpnVUx0WlhZK2pBT041Uy9GRW9segpNOGhvc1pEb2hXS05ZNEs1
                MzJRbzBZTXZMNFlzVVhYSFA4andSd0lEQVFBQkFvSUJBQlVSRWFoZFR0dWpFSU1XCkJzajRMY3lj
                S09GLzdXR3FnU1ZJMFYrR3Z2VFJOWTEyMGh0eURqU1FJYWVWbzVYR29ONWNhYTdocGM1ZStsYWoK
                Y1pGSUl0ZnArd1NVaXhnRkI5RWNONlQ1c0ErdXVLWFczb0ppRC9rekVWZ1pHTkkzRXZqVWJRM0VX
                MlFqaWRMbwpmdzQzRWUwakxNY01VTzgrYzl4WEJGUEUzUDlaQjVPZ3dIb3orQnhsMC95YTVaQkJ1
                TkN3TE9jZk1SajV4LzNhCllySS8vYmlSaDQ5U0VaMlhISUZSNldwUFlJSWgrYUs1SVRZdjBKRWd1
                QjVhaC9NbkduemFIbitEeU1wZ0JORFgKdVVFNXVpOU00TVdOQi9VclRMZWFjMUNLT3NxNk0ySW1E
                aUE1MXdNbm14NEhtbjdSNXVmUlhvK2Nzb3NrQ0o5RAo3NzI0dkVFQ2dZRUErOTF4cHJmMGtJTkVi
                YUhwODMrdW1IdW4rUTV2T29EMEx5bTRFa01zZ0lrcGpXVGtSUzd5CnVWWEM5YWUrSUgybzR2RHl6
                YjRqTHU3MEhEVWRpeHhZWHZBM3VxZnpGSnV0SEpHV0xOMXYrdkNXVG1NRlNPMUkKdmlrbDF6UEtC
                MVMxQW1reW5odDhBM1F1dmM5U3g3SmhjY25Nd0F1Y2ZzaUdEelExK2JDZGMxOENnWUVBeFB2aQpJ
                ZzBhMExrclJLTG1rN3gvUDZmT0xiRDFpdlRzZ0xXOWJJUC9mWUpSajNIeUhMMkkzbzNFVHMyUHpn
                NGZCVjFTClF2TTJuSUJOV1VTUjVLVTdRckhyMzZCbXFoVklNU3puanF5Q3l4NUx5bmdhRFNYbVI5
                cStzTlR2WVUwc2ZZS2YKSDUwZGE0ZFFzVllXOExvSER4b0ptTDhzQ2F1ZGhGZ3BqeDNpMUJrQ2dZ
                RUF0U0FKRFZZWklKdmw1OW1hdnl2QgpTWk1UdHYzMGEyUTFObjJRREVJV2pORVcrc0hsandNMk5x
                WkFNQjFUazFZSzBEbHF3eDdMZW9NSk5nZlVtU2ZuClBVOFBKTUtIQXZqNVF5UkhsVGdod1pxbTNQ
                UkU1cThOc3dNd1hWUzNJeEo5b2FBNWNJNWZYclI4c0srWjNsYWYKMFE3SW1ncy9uY1ZpOHlnZThO
                TmNSNDBDZ1lBck9ZNkVwRldIQ2FyNTg3a2ZJQlRZTmcxakwxcWlORjZWVzh3RwpQT3phY0xkTy85
                VCtBNFUrT09PajJ5MjhMSk1ZRFVOWTE1L2JOYmhEWjIyUU84WEdPOTZqZ3NJa2Zta0tDVzJDCmZF
                NXpIZUhKdXhNVVlZV25yTk45WUN4ck1KRWJ0WWNQVzkyeDA4NmNLMlQ3VEFieWhHY29zb0tLV0xO
                RzhFV20KVnd1SU9RS0JnRG5JK2xCV3hndCtoSDZxaHdTdklvUk5wU1diS3BEa21ZMnRFY2VZajhN
                enJRNTFKRmpjdDlGNgpHMFNQVzZRa1FQb2NNaDA5a1JFSmZEL3k4THE5SWhtY1VkekVuUFl0SDJ2
                NVNqb0s0WXhBZVhaK1FianR5U2VOCmsvMXUrVlVKMExpR3BNdytRckk3NWw3Q1JHYXdpak5IT3Ni
                R3gyYkUwWWwvWW5QVE5hbzQKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0KUEsDBAoAAAAA
                ADg3JlFjqsqiMgUAADIFAAAfAAAAMTU5OTM3NTQ2NjY3M19DQUNlcnRpZmljYXRlLmNydC0tLS0t
                QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEcWpDQ0FwS2dBd0lCQWdJVWIxZzNJNHlPT3JzQm5Q
                czlPdzhrYUsxS1dKb3dEUVlKS29aSWh2Y05BUUVMCkJRQXdiVEVMTUFrR0ExVUVCaE1DVlZNeEV6
                QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhFVEFQQmdOVkJBY1QKQ0ZOaGJpQktiM05sTVJRd0Vn
                WURWUVFLRXd0T2RYUmhibWw0TFVsdlZERUxNQWtHQTFVRUN4TUNRMEV4RXpBUgpCZ05WQkFNVENr
                NTFkR0Z1YVhnZ1EwRXdIaGNOTVRrd016RTRNVFF5TVRBd1doY05NalF3TXpFMk1UUXlNVEF3Cldq
                QnRNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVJNQThHQTFV
                RUJ4TUkKVTJGdUlFcHZjMlV4RkRBU0JnTlZCQW9UQzA1MWRHRnVhWGd0U1c5VU1Rc3dDUVlEVlFR
                TEV3SkRRVEVUTUJFRwpBMVVFQXhNS1RuVjBZVzVwZUNCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFF
                QkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFLS3JKd21vWnpLTTBtckE5UW8xNmRpWE5MUUtRTFhzOHpN
                WFBoTzZNc3QraWdUVEhXbTJCTWRoMUJDV0JKT2MKU29lQmNlM2VRR3R5WFhlZG41ZUxLTXNyZnJU
                RTRXQlFUOFVkTEQwU1g5ditIcmkvL3BDWVIyczBKQkNBRzMvYwo4RFhiQlpTQnNVVlovTTNDWnJx
                RTdyb2h2dS9PVjM5djJIZ0NuYmIwUzg1ditxeHZ6RWN0SU9rdjdjWGxsSDloCm13aGovNnNvU1hY
                Z1U0Z2V6dHZFSGZTU1M4dGI2aXAwV3R4WkFsL0QydHFCOHBFcDFRekRQWEhnNTFjS1NmY2gKckdu
                U0NCTGQ4ZXlqbjV5UnJCdW9vNSt2ZFM2NTNpZmF3OFJsMVR4MGsvcXlZTW9vd0NBR1YxMkZVVmRK
                S29KcQpEL3k1S3VSS3VOUDVzTDlBY2NRczFJa0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFE
                QWdFR01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGR3NIbVRJYkphUVFXd2VM
                ZTgwdnF2czdJY01BTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQnZ5TmprL3JEVjVwNmNjK2Ra
                emRJWDRKS3p4RFV2WVErcUpiYUdVVy94clJtSwpsTnlZQ2VodmtSS3ZUcHc4V0ltY1g3WlNSa3Bk
                UElDd1J6dTdDeDQrbDMyb1RweFlGUkhoLzdacWFhT0ZDajNHCk9ERWlPb2pTNzVTV2VFWG4rZCs0
                aC9KdERHL1R1bjViK1VhekFGMDdaa1dsQWVjcVEzNCtEM0ZPclhHKzF4K1EKNXhaN3NjQVdkK3p4
                YzNnSFNyb2lqa1p3Ty9odW9xTHR5V0IyVExDeVFKeVNkNEZIeDBnMlI4RFFPd1BteXhVTApLT0M2
                UU0yUzYzU3RBMHdROHRXa2ZLKzI2UFhUK1ZOdjBtdHFzL2U2WE00NW5uY000YWduZDdGV1plMUU0
                c0pzCjNuTTNyN3VLdnBJSEZoVUluRFhYTi90QllsUStaY0U1Zkh5QU5WN1oKLS0tLS1FTkQgQ0VS
                VElGSUNBVEUtLS0tLQpQSwECFAAKAAAAAAA4NyZRkI8P4KgFAACoBQAAHQAAAAAAAAAAAAAAAAAA
                AAAAMTU5OTM3NTQ2NjY3M19jZXJ0aWZpY2F0ZS5jcnRQSwECFAAKAAAAAAA4NyZRi74hbYsGAACL
                BgAAHAAAAAAAAAAAAAAAAADjBQAAMTU5OTM3NTQ2NjY3M19wcml2YXRlS2V5LmtleVBLAQIUAAoA
                AAAAADg3JlFjqsqiMgUAADIFAAAfAAAAAAAAAAAAAAAAAKgMAAAxNTk5Mzc1NDY2NjczX0NBQ2Vy
                dGlmaWNhdGUuY3J0UEsFBgAAAAADAAMA4gAAABcSAAAAAA\=\=

---
kind: Service
apiVersion: v1
metadata:
  name: barcode-reader-ui
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30003
  selector:
    app: barcode-reader