kind: Deployment
apiVersion: apps/v1
metadata:
  name: barcode-reader
  labels:
    app: barcode-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barcode-reader
  template:
    metadata:
      labels:
        app: barcode-reader
    spec:
      containers:
        - name: barcode-reader
          image: hexadtech/scanner-emulator:latest
          imagePullPolicy: Always
          ports:
            - name: flask-http
              containerPort: 5000
              hostPort: 5000
              protocol: TCP
          env:
            - name: MQTT_HOST
              value: "mqttserver-svc.default"
---
kind: Service
apiVersion: v1
metadata:
  name: barcode-reader-ui
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30003
  selector:
    app: barcode-reader